
    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;

    create table answers (
        answer_id integer generated by default as identity,
        is_correct boolean not null,
        order_number integer not null check (order_number>=1),
        question_id integer not null,
        created_at timestamp(6) not null,
        text varchar(50) not null,
        primary key (answer_id)
    );

    create table exams (
        created_by integer not null,
        exam_id integer generated by default as identity,
        is_public boolean not null,
        created_at timestamp(6) not null,
        exam_name varchar(50) not null,
        description varchar(255),
        primary key (exam_id)
    );

    create table paragraphs (
        created_by integer not null,
        is_public boolean not null,
        paragraph_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        primary key (paragraph_id)
    );

    create table part_details (
        order_number integer not null check (order_number>=1),
        paragraph_id integer,
        part_detail_id integer generated by default as identity,
        part_id integer,
        question_id integer,
        created_at timestamp(6) not null,
        primary key (part_detail_id)
    );

    create table parts (
        created_by integer not null,
        exam_id integer,
        is_public boolean not null,
        part_id integer generated by default as identity,
        created_at timestamp(6) not null,
        part_name varchar(50) not null,
        primary key (part_id)
    );

    create table questions (
        created_by integer not null,
        is_multiple_choice boolean not null,
        is_public boolean not null,
        paragraph_id integer,
        question_id integer generated by default as identity,
        created_at timestamp(6) not null,
        content varchar(255) not null,
        content_type varchar(255) check (content_type in ('TEXT','IMAGE','AUDIO')),
        description varchar(255) not null,
        primary key (question_id)
    );

    alter table if exists answers 
       add constraint FK3erw1a3t0r78st8ty27x6v3g1 
       foreign key (question_id) 
       references questions;

    alter table if exists part_details 
       add constraint FK3hbp8hucp6utac8rvisu9qrco 
       foreign key (paragraph_id) 
       references paragraphs;

    alter table if exists part_details 
       add constraint FK8b3mpdrlhfke9hhr2clspun3b 
       foreign key (part_id) 
       references parts;

    alter table if exists part_details 
       add constraint FKawfonawn82jra1etc9ot4wwdr 
       foreign key (question_id) 
       references questions;

    alter table if exists parts 
       add constraint FK5wvldjj34cpbt4avm0645q5ye 
       foreign key (exam_id) 
       references exams;

    alter table if exists questions 
       add constraint FKp0wu29kkp3teu5la7j7u6p4x9 
       foreign key (paragraph_id) 
       references paragraphs;
